FROM python:3.9-slim

WORKDIR /src

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install -e .

COPY . .

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8080"]